<a href="https://colab.research.google.com/github/HimanshuSahoo/PythonCode/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:

##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=10000

One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1163, 70, 2117, 7452], [1163, 70, 2117, 7963], [1163, 6774, 2117, 8685], [400, 5092, 6805, 6648, 7254], [400, 5092, 6805, 6648, 9738], [9554, 1163, 4144, 2117, 3832], [2996, 9307, 2351, 6648]]


Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1163   70 2117 7452]
 [   0    0    0    0 1163   70 2117 7963]
 [   0    0    0    0 1163 6774 2117 8685]
 [   0    0    0  400 5092 6805 6648 7254]
 [   0    0    0  400 5092 6805 6648 9738]
 [   0    0    0 9554 1163 4144 2117 3832]
 [   0    0    0    0 2996 9307 2351 6648]]


In [ ]:
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
    1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
    4.24572937e-02 -3.22833657e-05]
  [ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
    1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
    4.24572937e-02 -3.22833657e-05]
  [ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
    1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
    4.24572937e-02 -3.22833657e-05]
  [ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
    1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
    4.24572937e-02 -3.22833657e-05]
  [-1.46707669e-02  2.50866264e-03 -4.96991649e-02  4.35943268e-02
    2.36592442e-03 -1.89552065e-02  2.46800818e-02  1.31181739e-02
    3.98713984e-02 -4.60155271e-02]
  [ 2.26303600e-02  5.86374849e-03  2.67967023e-02 -2.74626017e-02
    1.55433528e-02  1.91438831e-02 -8.83505493e-03 -1.43815875e-02
   -8.17167759e-

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 1163,   70, 2117, 7452])

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
   1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
   4.24572937e-02 -3.22833657e-05]
 [ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
   1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
   4.24572937e-02 -3.22833657e-05]
 [ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
   1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
   4.24572937e-02 -3.22833657e-05]
 [ 1.76037662e-02  3.46957520e-03  2.17296593e-02 -4.31376956e-02
   1.34175308e-02 -9.36676189e-03  4.28127125e-03  1.46445744e-02
   4.24572937e-02 -3.22833657e-05]
 [-1.46707669e-02  2.50866264e-03 -4.96991649e-02  4.35943268e-02
   2.36592442e-03 -1.89552065e-02  2.46800818e-02  1.31181739e-02
   3.98713984e-02 -4.60155271e-02]
 [ 2.26303600e-02  5.86374849e-03  2.67967023e-02 -2.74626017e-02
   1.55433528e-02  1.91438831e-02 -8.83505493e-03 -1.43815875e-02
  -8.17167759e-03  8.13697651e-03